# ============================================
# NAMESPACE
# ============================================
# Agrupa recursos relacionados

apiVersion: v1
kind: Namespace
metadata:
  name: catalog-service
  labels:
    name: catalog-service
    environment: local