# ============================================
# DEPLOYMENT - Gestión de Pods
# ============================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: delivery-service
  namespace: delivery-service
  labels:
    app: delivery-service

spec:
  # ========================================
  # Número de réplicas (copias)
  # ========================================
  replicas: 1  # Empezamos con 1 pod

  # ========================================
  # Selector: ¿Qué pods gestionar?
  # ========================================
  selector:
    matchLabels:
      app: delivery-service

  # ========================================
  # Template: Cómo crear cada pod
  # ========================================
  template:
    metadata:
      labels:
        app: delivery-service

    spec:
      containers:
        - name: delivery-service

          # Imagen Docker
          image: delivery-service:1.0

          # imagePullPolicy:
          # - Never: Solo usar imagen local (desarrollo)
          # - Always: Siempre descargar (producción)
          imagePullPolicy: Never

          # Puerto del contenedor
          ports:
            - containerPort: 8087
              name: http

          # ====================================
          # VARIABLES DE ENTORNO
          # ====================================
          env:
            # Forzamos el perfil para que busque las variables ${}
            - name: SPRING_PROFILES_ACTIVE
              value: "kubernetes"

          envFrom:
            # Esto inyecta KAFKA_SERVERS, DB_URL, LOG_LEVEL, etc.
            - configMapRef:
                name: delivery-service-config
            # Esto inyecta DB_USERNAME, DB_PASSWORD, JWT_SECRET, etc.
            - secretRef:
                name: delivery-service-secret