CREATE TABLE deliveries (
    id BIGSERIAL PRIMARY KEY,
    order_id BIGINT NOT NULL,
    tracking_code VARCHAR(12) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'READY',
    delivery_address TEXT NOT NULL,
    delivered_at TIMESTAMP,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
