# ============================================
# CONFIGMAP - Configuración NO sensible
# ============================================
apiVersion: v1
kind: ConfigMap
metadata:
  name: order-service-config
  namespace: order-service
  labels:
    app: order-service

# Pares clave-valor
data:

  # ⭐ CLAVE: Usa el nombre del Service de product-service
  CATALOG_SERVICE_URL: "http://catalog-service.catalog-service.svc.cluster.local"
  USER_SERVICE_URL: "http://user-service.user-service.svc.cluster.local"
  KAFKA_SERVERS: "host.docker.internal:9093"

  # URL de la base de datos
  # host.docker.internal apunta a localhost de tu máquina
  DB_URL: "jdbc:postgresql://host.docker.internal:5436/orderdb"

  # Configuración de JPA
  DDL_AUTO: "validate"
  SHOW_SQL: "false"

  # Pool de conexiones
  POOL_SIZE: "10"

  # Logging
  LOG_LEVEL: "INFO"
  SQL_LOG_LEVEL: "WARN"

  # JVM
  JAVA_OPTS: "-Xmx512m -Xms256m"