# ============================================
# DEPLOYMENT - Gestión de Pods (Versión Final)
# ============================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: order-service
  labels:
    app: order-service

spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service

  template:
    metadata:
      labels:
        app: order-service

    spec:
      containers:
        - name: order-service
          image: order-service:1.0
          imagePullPolicy: Never
          ports:
            - containerPort: 8085
              name: http

          # ====================================
          # VARIABLES DE ENTORNO
          # ====================================
          env:
            # Forzamos el perfil para que busque las variables ${}
            - name: SPRING_PROFILES_ACTIVE
              value: "kubernetes"

          envFrom:
            # Esto inyecta KAFKA_SERVERS, DB_URL, LOG_LEVEL, etc.
            - configMapRef:
                name: order-service-config
            # Esto inyecta DB_USERNAME, DB_PASSWORD, JWT_SECRET, etc.
            - secretRef:
                name: order-service-secret